# Generated by Django 5.1.6 on 2025-02-17 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanapwedeApp', '0004_jobpost_posted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='posted_by',
            field=models.ForeignKey(limit_choices_to={'user_type': 'Employer'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.ManyToManyField(blank=True, to='hanapwedeApp.tag'),
        ),
    ]
