# Generated by Django 5.1.2 on 2025-02-22 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanapwedeApp', '0006_remove_jobpost_tags_jobpost_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisabilityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDisabilityTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeeprofile',
            name='disability_type',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='disabilitytag',
            field=models.ManyToManyField(blank=True, to='hanapwedeApp.disabilitytag'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='user_disablitytag',
            field=models.ManyToManyField(blank=True, to='hanapwedeApp.userdisabilitytag'),
        ),
    ]
