# Generated by Django 5.1.2 on 2025-02-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanapwedeApp', '0007_disabilitytag_userdisabilitytag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary_range',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
