# Generated by Django 5.1.2 on 2025-02-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanapwedeApp', '0013_report_post_alter_report_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
