# Generated by Django 5.1.6 on 2025-02-24 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanapwedeApp', '0014_report_report_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
