# Generated by Django 5.1.6 on 2025-03-13 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanapwedeApp', '0017_chatrooms_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='ID_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='user_disability',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
