# Generated by Django 5.1.6 on 2025-03-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanapwedeApp', '0018_employeeprofile_id_no_employeeprofile_activated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
