# Generated by Django 5.1.6 on 2025-03-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanapwedeApp', '0020_application_applicant'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='employee_resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
