# Generated by Django 5.1.6 on 2025-04-06 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanapwedeApp', '0024_remove_jobfair_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFairJobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jobfair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hanapwedeApp.jobfair')),
                ('jobpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hanapwedeApp.jobpost')),
            ],
            options={
                'unique_together': {('jobfair', 'jobpost')},
            },
        ),
    ]
