# Generated by Django 5.1.6 on 2025-04-07 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanapwedeApp', '0025_jobfairjobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_fair',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='hanapwedeApp.jobfair'),
        ),
    ]
