# Generated by Django 5.1.6 on 2025-04-10 17:25

import hanapwedeApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hanapwedeApp', '0028_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=hanapwedeApp.models.user_directory_path),
        ),
    ]
